volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      # Referenciando as variáveis do arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: email_sender
    ports:
      - "5432:5432"
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts de inicialização
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html
      # Configuração do Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # Código da aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - web
      - banco
      - fila
    depends_on:
      - db
      - queue
    environment:
      # Referenciando as variáveis do arquivo .env
      DB_NAME: email_sender
      DB_HOST: ${DB_HOST}
      DB_USER: ${POSTGRES_USER} # Reutilizando a variável
      DB_PASSWORD: ${POSTGRES_PASSWORD} # Reutilizando a variável
      REDIS_HOST: ${REDIS_HOST}
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      # Código do worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379